GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAzODMwNzg0LCJleHAiOjE3MDM4MzA3OTl9.Yg8rnXQlv-nvRYrIBFmIfLVpsSXoraSccCVWOexrlgA



###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAzODMxMTExfQ.vWZf1Q9DnRTGvcxo_gfrY1cc-bDJWuCc3Sz1E2S4V3E"

}

###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAzODMxMTExfQ.vWZf1Q9DnRTGvcxo_gfrY1cc-bDJWuCc3Sz1E2S4V3E"
}



###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}
